version: "3"

services:
  go-api:
    container_name: go-api
    build:
      context: ./go-api
      dockerfile: Dockerfile.dev
    volumes:
      - ./go-api:/app
    environment:
      - DB_HOST=sqlite-db
      - REDIS_HOST=redis
    depends_on:
      - sqlite-db
      - redis
    networks:
      - app-network

  sqlite-db:
    container_name: sqlite-db
    image: nouchka/sqlite3:latest
    volumes:
      - ./data:/data
    
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "9000:80"
    depends_on:
      - go-api
      - next-fe
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:7.2.5

  next-fe:
    container_name: next-fe
    build:
      context: ./next-fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./next-fe:/app
    env_file:
      - ./next-fe/.env.development
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge