# Go API Dockerfile
FROM golang:1.22.3

# Install air - Hot reloading package for Go
RUN go install github.com/cosmtrek/air@latest

# Set the working directory is /app inside docker container
WORKDIR /app

# Copy dependencies config files to container's /app folder
COPY go.mod ./
COPY go.sum ./
# Run to install all required dependencies
RUN go mod download

# Copy all files to active working directory inside container
COPY . .

# Use air to run the Go API with live reloading
# CMD ["air", "-c", "./.air.toml"]
CMD ["air"]
